controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
price_calculation:
    path: /price-calculation
    controller: App\Controller\PriceCalculationController::index